/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedResourcesResourceRouteImport } from './routes/_authed/resources.$resource'
import { Route as AuthedResourcesResourceIdRouteImport } from './routes/_authed/resources.$resource.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedResourcesResourceRoute = AuthedResourcesResourceRouteImport.update({
  id: '/resources/$resource',
  path: '/resources/$resource',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedResourcesResourceIdRoute =
  AuthedResourcesResourceIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthedResourcesResourceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/api/health': typeof ApiHealthRoute
  '/resources/$resource': typeof AuthedResourcesResourceRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/resources/$resource/$id': typeof AuthedResourcesResourceIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/api/health': typeof ApiHealthRoute
  '/': typeof AuthedIndexRoute
  '/resources/$resource': typeof AuthedResourcesResourceRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/resources/$resource/$id': typeof AuthedResourcesResourceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/api/health': typeof ApiHealthRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/resources/$resource': typeof AuthedResourcesResourceRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/resources/$resource/$id': typeof AuthedResourcesResourceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/health'
    | '/resources/$resource'
    | '/api/auth/$'
    | '/resources/$resource/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/api/health'
    | '/'
    | '/resources/$resource'
    | '/api/auth/$'
    | '/resources/$resource/$id'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/api/health'
    | '/_authed/'
    | '/_authed/resources/$resource'
    | '/api/auth/$'
    | '/_authed/resources/$resource/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/resources/$resource': {
      id: '/_authed/resources/$resource'
      path: '/resources/$resource'
      fullPath: '/resources/$resource'
      preLoaderRoute: typeof AuthedResourcesResourceRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/resources/$resource/$id': {
      id: '/_authed/resources/$resource/$id'
      path: '/$id'
      fullPath: '/resources/$resource/$id'
      preLoaderRoute: typeof AuthedResourcesResourceIdRouteImport
      parentRoute: typeof AuthedResourcesResourceRoute
    }
  }
}

interface AuthedResourcesResourceRouteChildren {
  AuthedResourcesResourceIdRoute: typeof AuthedResourcesResourceIdRoute
}

const AuthedResourcesResourceRouteChildren: AuthedResourcesResourceRouteChildren =
  {
    AuthedResourcesResourceIdRoute: AuthedResourcesResourceIdRoute,
  }

const AuthedResourcesResourceRouteWithChildren =
  AuthedResourcesResourceRoute._addFileChildren(
    AuthedResourcesResourceRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedResourcesResourceRoute: typeof AuthedResourcesResourceRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedResourcesResourceRoute: AuthedResourcesResourceRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
