import config from '../../eslint.config.mjs';

export default [
  ...config,
  {
    // Generated by the TanStack Router plugin; build output and Nitro artifacts.
    ignores: ['src/routeTree.gen.ts', '.output/**', '.nitro/**'],
  },
];
