// @ts-check

/**
 * Fingerprint configuration for the EAS `fingerprint` runtimeVersion policy.
 *
 * `ios/` and `android/` are generated by `expo prebuild` (Continuous Native Generation) and are
 * gitignored, so they never live in the committed source. EAS regenerates them during the build,
 * which made the build-time fingerprint include a `bareNativeDir` that the source-side fingerprint
 * did not, so the two runtime versions diverged and the "Configure Expo Updates" step failed.
 *
 * Excluding the generated native dirs keeps the fingerprint identical across a clean checkout and an
 * EAS build. The runtime-relevant native surface (native deps under node_modules, config plugins,
 * app config) is still hashed, so OTA-update compatibility is preserved.
 *
 * @type {import('@expo/fingerprint').Config}
 */
module.exports = {
  ignorePaths: ['ios', 'ios/**/*', 'android', 'android/**/*'],
};
