/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List records */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A list of records. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecordList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/records/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a record by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The requested record. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Record"];
                    };
                };
                /** @description Record not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RecordList: {
            records: components["schemas"]["Record"][];
            total: number;
        };
        Record: {
            /** @example clz0a1b2c3d4e5f6g7h8i9j0 */
            id: string;
            /** @example Midnight Grooves */
            title: string;
            /** @example The Turntables */
            artist: string;
            /** @example 1979 */
            year: number | null;
            /**
             * Format: uri
             * @example https://example.com/cover.jpg
             */
            coverArtUrl: string | null;
            /**
             * Format: uri
             * @example https://example.com/preview.mp3
             */
            previewUrl: string | null;
            /** @example discogs */
            source: string;
            /** @example 123456 */
            externalId: string;
            /**
             * Format: uri
             * @example https://www.discogs.com/release/123456
             */
            sourceUrl: string | null;
            /** @example 24.99 */
            price: number | null;
            /** @example USD */
            currency: string | null;
            /** @example in_stock */
            availability: string | null;
            /**
             * Format: date-time
             * @example 2026-06-01T12:00:00.000Z
             */
            scrapedAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        Error: {
            error: string;
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
