import { tv } from "tailwind-variants";

const textColorVariants = {
	accent: "",
	"accent-soft": "",
	"accent-softest": "",
	"accent-disabled": "",
	"accent-on-solid": "",
	amber: "",
	"amber-soft": "",
	"amber-softest": "",
	"amber-disabled": "",
	"amber-on-solid": "",
	blue: "",
	"blue-soft": "",
	"blue-softest": "",
	"blue-disabled": "",
	"blue-on-solid": "",
	bronze: "",
	"bronze-soft": "",
	"bronze-softest": "",
	"bronze-disabled": "",
	"bronze-on-solid": "",
	brown: "",
	"brown-soft": "",
	"brown-softest": "",
	"brown-disabled": "",
	"brown-on-solid": "",
	crimson: "",
	"crimson-soft": "",
	"crimson-softest": "",
	"crimson-disabled": "",
	"crimson-on-solid": "",
	critical: "",
	"critical-soft": "",
	"critical-softest": "",
	"critical-disabled": "",
	"critical-on-solid": "",
	cyan: "",
	"cyan-soft": "",
	"cyan-softest": "",
	"cyan-disabled": "",
	"cyan-on-solid": "",
	gold: "",
	"gold-soft": "",
	"gold-softest": "",
	"gold-disabled": "",
	"gold-on-solid": "",
	grass: "",
	"grass-soft": "",
	"grass-softest": "",
	"grass-disabled": "",
	"grass-on-solid": "",
	gray: "",
	"gray-soft": "",
	"gray-softest": "",
	"gray-disabled": "",
	"gray-on-solid": "",
	green: "",
	"green-soft": "",
	"green-softest": "",
	"green-disabled": "",
	"green-on-solid": "",
	indigo: "",
	"indigo-soft": "",
	"indigo-softest": "",
	"indigo-disabled": "",
	"indigo-on-solid": "",
	info: "",
	"info-soft": "",
	"info-softest": "",
	"info-disabled": "",
	"info-on-solid": "",
	iris: "",
	"iris-soft": "",
	"iris-softest": "",
	"iris-disabled": "",
	"iris-on-solid": "",
	jade: "",
	"jade-soft": "",
	"jade-softest": "",
	"jade-disabled": "",
	"jade-on-solid": "",
	lime: "",
	"lime-soft": "",
	"lime-softest": "",
	"lime-disabled": "",
	"lime-on-solid": "",
	mauve: "",
	"mauve-soft": "",
	"mauve-softest": "",
	"mauve-disabled": "",
	"mauve-on-solid": "",
	mint: "",
	"mint-soft": "",
	"mint-softest": "",
	"mint-disabled": "",
	"mint-on-solid": "",
	neutral: "",
	"neutral-soft": "",
	"neutral-softest": "",
	"neutral-disabled": "",
	"neutral-on-intense": "",
	"neutral-on-solid": "",
	olive: "",
	"olive-soft": "",
	"olive-softest": "",
	"olive-disabled": "",
	"olive-on-solid": "",
	orange: "",
	"orange-soft": "",
	"orange-softest": "",
	"orange-disabled": "",
	"orange-on-solid": "",
	pink: "",
	"pink-soft": "",
	"pink-softest": "",
	"pink-disabled": "",
	"pink-on-solid": "",
	plum: "",
	"plum-soft": "",
	"plum-softest": "",
	"plum-disabled": "",
	"plum-on-solid": "",
	positive: "",
	"positive-soft": "",
	"positive-softest": "",
	"positive-disabled": "",
	"positive-on-solid": "",
	purple: "",
	"purple-soft": "",
	"purple-softest": "",
	"purple-disabled": "",
	"purple-on-solid": "",
	red: "",
	"red-soft": "",
	"red-softest": "",
	"red-disabled": "",
	"red-on-solid": "",
	ruby: "",
	"ruby-soft": "",
	"ruby-softest": "",
	"ruby-disabled": "",
	"ruby-on-solid": "",
	sage: "",
	"sage-soft": "",
	"sage-softest": "",
	"sage-disabled": "",
	"sage-on-solid": "",
	sand: "",
	"sand-soft": "",
	"sand-softest": "",
	"sand-disabled": "",
	"sand-on-solid": "",
	sky: "",
	"sky-soft": "",
	"sky-softest": "",
	"sky-disabled": "",
	"sky-on-solid": "",
	slate: "",
	"slate-soft": "",
	"slate-softest": "",
	"slate-disabled": "",
	"slate-on-solid": "",
	teal: "",
	"teal-soft": "",
	"teal-softest": "",
	"teal-disabled": "",
	"teal-on-solid": "",
	tomato: "",
	"tomato-soft": "",
	"tomato-softest": "",
	"tomato-disabled": "",
	"tomato-on-solid": "",
	violet: "",
	"violet-soft": "",
	"violet-softest": "",
	"violet-disabled": "",
	"violet-on-solid": "",
	warning: "",
	"warning-soft": "",
	"warning-softest": "",
	"warning-disabled": "",
	"warning-on-solid": "",
	yellow: "",
	"yellow-soft": "",
	"yellow-softest": "",
	"yellow-disabled": "",
	"yellow-on-solid": "",
	white: "",
	black: "",
} as const;

const textColorCompoundVariants = [
	{ color: "accent", className: "text-accent" },
	{ color: "accent-soft", className: "text-accent-soft" },
	{ color: "accent-softest", className: "text-accent-softest" },
	{ color: "accent-disabled", className: "text-accent-disabled" },
	{ color: "accent-on-solid", className: "text-accent-on-solid" },
	{ color: "amber", className: "text-amber" },
	{ color: "amber-soft", className: "text-amber-soft" },
	{ color: "amber-softest", className: "text-amber-softest" },
	{ color: "amber-disabled", className: "text-amber-disabled" },
	{ color: "amber-on-solid", className: "text-amber-on-solid" },
	{ color: "blue", className: "text-blue" },
	{ color: "blue-soft", className: "text-blue-soft" },
	{ color: "blue-softest", className: "text-blue-softest" },
	{ color: "blue-disabled", className: "text-blue-disabled" },
	{ color: "blue-on-solid", className: "text-blue-on-solid" },
	{ color: "bronze", className: "text-bronze" },
	{ color: "bronze-soft", className: "text-bronze-soft" },
	{ color: "bronze-softest", className: "text-bronze-softest" },
	{ color: "bronze-disabled", className: "text-bronze-disabled" },
	{ color: "bronze-on-solid", className: "text-bronze-on-solid" },
	{ color: "brown", className: "text-brown" },
	{ color: "brown-soft", className: "text-brown-soft" },
	{ color: "brown-softest", className: "text-brown-softest" },
	{ color: "brown-disabled", className: "text-brown-disabled" },
	{ color: "brown-on-solid", className: "text-brown-on-solid" },
	{ color: "crimson", className: "text-crimson" },
	{ color: "crimson-soft", className: "text-crimson-soft" },
	{ color: "crimson-softest", className: "text-crimson-softest" },
	{ color: "crimson-disabled", className: "text-crimson-disabled" },
	{ color: "crimson-on-solid", className: "text-crimson-on-solid" },
	{ color: "critical", className: "text-critical" },
	{ color: "critical-soft", className: "text-critical-soft" },
	{ color: "critical-softest", className: "text-critical-softest" },
	{ color: "critical-disabled", className: "text-critical-disabled" },
	{ color: "critical-on-solid", className: "text-critical-on-solid" },
	{ color: "cyan", className: "text-cyan" },
	{ color: "cyan-soft", className: "text-cyan-soft" },
	{ color: "cyan-softest", className: "text-cyan-softest" },
	{ color: "cyan-disabled", className: "text-cyan-disabled" },
	{ color: "cyan-on-solid", className: "text-cyan-on-solid" },
	{ color: "gold", className: "text-gold" },
	{ color: "gold-soft", className: "text-gold-soft" },
	{ color: "gold-softest", className: "text-gold-softest" },
	{ color: "gold-disabled", className: "text-gold-disabled" },
	{ color: "gold-on-solid", className: "text-gold-on-solid" },
	{ color: "grass", className: "text-grass" },
	{ color: "grass-soft", className: "text-grass-soft" },
	{ color: "grass-softest", className: "text-grass-softest" },
	{ color: "grass-disabled", className: "text-grass-disabled" },
	{ color: "grass-on-solid", className: "text-grass-on-solid" },
	{ color: "gray", className: "text-gray" },
	{ color: "gray-soft", className: "text-gray-soft" },
	{ color: "gray-softest", className: "text-gray-softest" },
	{ color: "gray-disabled", className: "text-gray-disabled" },
	{ color: "gray-on-solid", className: "text-gray-on-solid" },
	{ color: "green", className: "text-green" },
	{ color: "green-soft", className: "text-green-soft" },
	{ color: "green-softest", className: "text-green-softest" },
	{ color: "green-disabled", className: "text-green-disabled" },
	{ color: "green-on-solid", className: "text-green-on-solid" },
	{ color: "indigo", className: "text-indigo" },
	{ color: "indigo-soft", className: "text-indigo-soft" },
	{ color: "indigo-softest", className: "text-indigo-softest" },
	{ color: "indigo-disabled", className: "text-indigo-disabled" },
	{ color: "indigo-on-solid", className: "text-indigo-on-solid" },
	{ color: "info", className: "text-info" },
	{ color: "info-soft", className: "text-info-soft" },
	{ color: "info-softest", className: "text-info-softest" },
	{ color: "info-disabled", className: "text-info-disabled" },
	{ color: "info-on-solid", className: "text-info-on-solid" },
	{ color: "iris", className: "text-iris" },
	{ color: "iris-soft", className: "text-iris-soft" },
	{ color: "iris-softest", className: "text-iris-softest" },
	{ color: "iris-disabled", className: "text-iris-disabled" },
	{ color: "iris-on-solid", className: "text-iris-on-solid" },
	{ color: "jade", className: "text-jade" },
	{ color: "jade-soft", className: "text-jade-soft" },
	{ color: "jade-softest", className: "text-jade-softest" },
	{ color: "jade-disabled", className: "text-jade-disabled" },
	{ color: "jade-on-solid", className: "text-jade-on-solid" },
	{ color: "lime", className: "text-lime" },
	{ color: "lime-soft", className: "text-lime-soft" },
	{ color: "lime-softest", className: "text-lime-softest" },
	{ color: "lime-disabled", className: "text-lime-disabled" },
	{ color: "lime-on-solid", className: "text-lime-on-solid" },
	{ color: "mauve", className: "text-mauve" },
	{ color: "mauve-soft", className: "text-mauve-soft" },
	{ color: "mauve-softest", className: "text-mauve-softest" },
	{ color: "mauve-disabled", className: "text-mauve-disabled" },
	{ color: "mauve-on-solid", className: "text-mauve-on-solid" },
	{ color: "mint", className: "text-mint" },
	{ color: "mint-soft", className: "text-mint-soft" },
	{ color: "mint-softest", className: "text-mint-softest" },
	{ color: "mint-disabled", className: "text-mint-disabled" },
	{ color: "mint-on-solid", className: "text-mint-on-solid" },
	{ color: "neutral", className: "text-neutral" },
	{ color: "neutral-soft", className: "text-neutral-soft" },
	{ color: "neutral-softest", className: "text-neutral-softest" },
	{ color: "neutral-disabled", className: "text-neutral-disabled" },
	{ color: "neutral-on-intense", className: "text-neutral-on-intense" },
	{ color: "neutral-on-solid", className: "text-neutral-on-solid" },
	{ color: "olive", className: "text-olive" },
	{ color: "olive-soft", className: "text-olive-soft" },
	{ color: "olive-softest", className: "text-olive-softest" },
	{ color: "olive-disabled", className: "text-olive-disabled" },
	{ color: "olive-on-solid", className: "text-olive-on-solid" },
	{ color: "orange", className: "text-orange" },
	{ color: "orange-soft", className: "text-orange-soft" },
	{ color: "orange-softest", className: "text-orange-softest" },
	{ color: "orange-disabled", className: "text-orange-disabled" },
	{ color: "orange-on-solid", className: "text-orange-on-solid" },
	{ color: "pink", className: "text-pink" },
	{ color: "pink-soft", className: "text-pink-soft" },
	{ color: "pink-softest", className: "text-pink-softest" },
	{ color: "pink-disabled", className: "text-pink-disabled" },
	{ color: "pink-on-solid", className: "text-pink-on-solid" },
	{ color: "plum", className: "text-plum" },
	{ color: "plum-soft", className: "text-plum-soft" },
	{ color: "plum-softest", className: "text-plum-softest" },
	{ color: "plum-disabled", className: "text-plum-disabled" },
	{ color: "plum-on-solid", className: "text-plum-on-solid" },
	{ color: "positive", className: "text-positive" },
	{ color: "positive-soft", className: "text-positive-soft" },
	{ color: "positive-softest", className: "text-positive-softest" },
	{ color: "positive-disabled", className: "text-positive-disabled" },
	{ color: "positive-on-solid", className: "text-positive-on-solid" },
	{ color: "purple", className: "text-purple" },
	{ color: "purple-soft", className: "text-purple-soft" },
	{ color: "purple-softest", className: "text-purple-softest" },
	{ color: "purple-disabled", className: "text-purple-disabled" },
	{ color: "purple-on-solid", className: "text-purple-on-solid" },
	{ color: "red", className: "text-red" },
	{ color: "red-soft", className: "text-red-soft" },
	{ color: "red-softest", className: "text-red-softest" },
	{ color: "red-disabled", className: "text-red-disabled" },
	{ color: "red-on-solid", className: "text-red-on-solid" },
	{ color: "ruby", className: "text-ruby" },
	{ color: "ruby-soft", className: "text-ruby-soft" },
	{ color: "ruby-softest", className: "text-ruby-softest" },
	{ color: "ruby-disabled", className: "text-ruby-disabled" },
	{ color: "ruby-on-solid", className: "text-ruby-on-solid" },
	{ color: "sage", className: "text-sage" },
	{ color: "sage-soft", className: "text-sage-soft" },
	{ color: "sage-softest", className: "text-sage-softest" },
	{ color: "sage-disabled", className: "text-sage-disabled" },
	{ color: "sage-on-solid", className: "text-sage-on-solid" },
	{ color: "sand", className: "text-sand" },
	{ color: "sand-soft", className: "text-sand-soft" },
	{ color: "sand-softest", className: "text-sand-softest" },
	{ color: "sand-disabled", className: "text-sand-disabled" },
	{ color: "sand-on-solid", className: "text-sand-on-solid" },
	{ color: "sky", className: "text-sky" },
	{ color: "sky-soft", className: "text-sky-soft" },
	{ color: "sky-softest", className: "text-sky-softest" },
	{ color: "sky-disabled", className: "text-sky-disabled" },
	{ color: "sky-on-solid", className: "text-sky-on-solid" },
	{ color: "slate", className: "text-slate" },
	{ color: "slate-soft", className: "text-slate-soft" },
	{ color: "slate-softest", className: "text-slate-softest" },
	{ color: "slate-disabled", className: "text-slate-disabled" },
	{ color: "slate-on-solid", className: "text-slate-on-solid" },
	{ color: "teal", className: "text-teal" },
	{ color: "teal-soft", className: "text-teal-soft" },
	{ color: "teal-softest", className: "text-teal-softest" },
	{ color: "teal-disabled", className: "text-teal-disabled" },
	{ color: "teal-on-solid", className: "text-teal-on-solid" },
	{ color: "tomato", className: "text-tomato" },
	{ color: "tomato-soft", className: "text-tomato-soft" },
	{ color: "tomato-softest", className: "text-tomato-softest" },
	{ color: "tomato-disabled", className: "text-tomato-disabled" },
	{ color: "tomato-on-solid", className: "text-tomato-on-solid" },
	{ color: "violet", className: "text-violet" },
	{ color: "violet-soft", className: "text-violet-soft" },
	{ color: "violet-softest", className: "text-violet-softest" },
	{ color: "violet-disabled", className: "text-violet-disabled" },
	{ color: "violet-on-solid", className: "text-violet-on-solid" },
	{ color: "warning", className: "text-warning" },
	{ color: "warning-soft", className: "text-warning-soft" },
	{ color: "warning-softest", className: "text-warning-softest" },
	{ color: "warning-disabled", className: "text-warning-disabled" },
	{ color: "warning-on-solid", className: "text-warning-on-solid" },
	{ color: "yellow", className: "text-yellow" },
	{ color: "yellow-soft", className: "text-yellow-soft" },
	{ color: "yellow-softest", className: "text-yellow-softest" },
	{ color: "yellow-disabled", className: "text-yellow-disabled" },
	{ color: "yellow-on-solid", className: "text-yellow-on-solid" },
	{ color: "white", className: "text-white" },
	{ color: "black", className: "text-black" },
] as const;

export const textRecipe = tv({
	base: "",
	variants: {
		size: {
			inherit: "text-inherit",
			"2xs": "",
			xs: "	",
			sm: "",
			md: "",
			lg: "",
			xl: "",
			"2xl": "",
			"3xl": "",
			"4xl": "",
			"5xl": "",
			"6xl": "",
			"7xl": "",
			"8xl": "",
			"9xl": "",
		},
		transform: {
			none: "",
			uppercase: "uppercase",
			lowercase: "lowercase",
			capitalize: "capitalize",
		},
		family: {
			polymath: "",
		},
		weight: {
			regular: "",
			medium: "",
			semibold: "",
			bold: "",
		},
		variant: {
			display: "",
			default: "",
			text: "",
		},
		align: {
			left: "text-left",
			center: "text-center",
			right: "text-right",
		},
		color: textColorVariants,
		multiline: {
			true: "",
			false: "",
		},
		decoration: {
			none: "",
			underline: "underline",
			lineThrough: "line-through",
			strikethrough: "strikethrough",
		},
		tabularNums: {
			true: "tabular-nums",
			false: "",
		},
	},
	compoundVariants: [
		...textColorCompoundVariants,
		{
			multiline: true,
			size: "2xs",
			className: "leading-[14px]",
		},
		{ multiline: true, size: "xs", className: "leading-[16px]" },
		{ multiline: true, size: "sm", className: "leading-[20px]" },
		{ multiline: true, size: "md", className: "leading-[32px]" },
		{ multiline: true, size: "lg", className: "leading-[24px]" },
		{ multiline: true, size: "xl", className: "leading-[26px]" },
		{ multiline: true, size: "2xl", className: "leading-[30px]" },
		{ multiline: true, size: "3xl", className: "leading-[40px]" },
		{ multiline: true, size: "4xl", className: "leading-[50px]" },
		{ multiline: true, size: "5xl", className: "leading-[56px]" },
		{ multiline: true, size: "6xl", className: "leading-[64px]" },
		{ multiline: true, size: "7xl", className: "leading-[72px]" },
		{ multiline: true, size: "8xl", className: "leading-[88px]" },
		{ multiline: true, size: "9xl", className: "leading-[92px]" },

		{
			family: "polymath",
			variant: "default",
			weight: "regular",
			className: "font-polymath-medium",
		},
		{
			family: "polymath",
			variant: "default",
			weight: "medium",
			className: "font-polymath-medium",
		},
		{
			family: "polymath",
			variant: "default",
			weight: "semibold",
			className: "font-polymath-semibold",
		},
		{
			family: "polymath",
			variant: "default",
			weight: "bold",
			className: "font-polymath-bold",
		},

		{
			family: "polymath",
			variant: "display",
			weight: "regular",
			className: "font-polymath-display-medium",
		},
		{
			family: "polymath",
			variant: "display",
			weight: "medium",
			className: "font-polymath-display-medium",
		},
		{
			family: "polymath",
			variant: "display",
			weight: "semibold",
			className: "font-polymath-display-semibold",
		},
		{
			family: "polymath",
			variant: "display",
			weight: "bold",
			className: "font-polymath-display-bold",
		},

		{
			family: "polymath",
			variant: "text",
			weight: "regular",
			className: "font-polymath-text-regular",
		},
		{
			family: "polymath",
			variant: "text",
			weight: "medium",
			className: "font-polymath-text-medium",
		},
		{
			family: "polymath",
			variant: "text",
			weight: "semibold",
			className: "font-polymath-text-semibold",
		},
		{
			family: "polymath",
			variant: "text",
			weight: "bold",
			className: "font-polymath-text-bold",
		},
		{
			family: "polymath",
			size: "2xs",
			className: "text-[10px]",
		},
		{
			family: "polymath",
			size: "xs",
			className: "text-[12px]",
		},
		{
			family: "polymath",
			size: "sm",
			className: "text-[14px]",
		},
		{
			family: "polymath",
			size: "md",
			className: "text-[16px]",
		},
		{
			family: "polymath",
			size: "lg",
			className: "text-[18px]",
		},
		{
			family: "polymath",
			size: "xl",
			className: "text-[20px]",
		},
		{
			family: "polymath",
			size: "2xl",
			className: "text-[24px]",
		},
		{
			family: "polymath",
			size: "3xl",
			className: "text-[30px]",
		},
		{
			family: "polymath",
			size: "4xl",
			className: "text-[36px]",
		},
		{
			family: "polymath",
			size: "5xl",
			className: "text-[48px]",
		},
		{
			family: "polymath",
			size: "6xl",
			className: "text-[60px]",
		},
		{
			family: "polymath",
			size: "7xl",
			className: "text-[72px]",
		},
		{
			family: "polymath",
			size: "8xl",
			className: "text-[96px]",
		},
		{
			family: "polymath",
			size: "9xl",
			className: "text-[128px]",
		},
	],
	defaultVariants: {
		size: "md",
		color: "neutral",
		weight: "regular",
		transform: "none",
		align: "left",
		multiline: false,
		variant: "default",
		family: "polymath",
	},
});
